/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NutSwitch: typeof import('@nutui/nutui-taro')['Switch']
    Result: typeof import('./../src/components/Result/Result.vue')['default']
    Scene: typeof import('./../src/components/Scene/Scene.vue')['default']
  }
}
